apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets-kv
  namespace: database
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "acadf60e-b9ea-4254-b86e-a0d23f057c21"
    keyvaultName: "akskeyvault"
    tenantID: "512ec501-cb12-46d1-bbef-7f52f8ad2df8"
    objects:  |
      array:
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-db
          objectType: secret
  secretObjects:
  - secretName: postgress-secret
    type: Opaque
    data:
      - objectName: postgres-password
        key: password
      - objectName: postgres-user
        key: user
      - objectName: postgres-db
        key: db